import type { NextPage } from 'next'
import { useState, useEffect } from 'react'
import Head from 'next/head'
import Top from '../components/Top'
import Main from '../components/Main'
import { ThemeContext, ThemeTypes, themes, getInitialTheme } from "../components/context/theme";

const Home: NextPage = () => {
  const [theme, setTheme] = useState<ThemeTypes>(themes.light)
  
  const toggleTheme = () => {
    setTheme( (prev) => {
      localStorage.setItem('theme_mode', prev === themes.dark ? 'light' : 'dark');
      return prev === themes.dark ? themes.light : themes.dark
    })
  }

  useEffect(() => {
    const themeMode = localStorage.getItem('theme_mode')
    const theme = themes[themeMode as keyof typeof themes]
    setTheme(theme ? theme : getInitialTheme())
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App 🤔</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeContext.Provider value={{ theme, toggleTheme }}>
        <style jsx global>{`
          body {
            color: ${theme.foreground};
            background: ${theme.background};
            transition: 255ms ease;
          }
        `}</style>

        <Top />

        <Main />

        <footer></footer>
      </ThemeContext.Provider>
    </>
  )
}

export default Home
